obstacle_range: 2.5
raytrace_range: 3.0
transform_tolerance: 0.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflater:
  robot_radius: 0.2
  inflation_radius: 0.50


obstacles:
  observation_sources: base_scan head_xtion
  enabled: true
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  combination_method: 1

  base_scan:
    data_type: LaserScan
    topic: hsrb/base_scan
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.11
    max_obstacle_height: 0.3

  head_xtion:
    data_type: PointCloud2
    topic: hsrb/head_rgbd_sensor/depth_registered/rectified_points
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.02
    max_obstacle_height: 0.1

map_topic: "/map"
global_frame: map
robot_base_frame: base_footprint
update_frequency: 1.0
publish_frequency: 0.5
static_map: true

plugins:
 - {name: static_map, type: "costmap_2d::StaticLayer"}
 - {name: obstacles,  type: "costmap_2d::ObstacleLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}
