DWAPlannerROS:
  acc_lim_theta: 15.0
  acc_lim_trans: 0.1
  acc_lim_x: 3.0
  acc_lim_y: 3.0
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 0.8
  max_rot_vel: 1.5
  max_scaling_factor: 0.2
  max_trans_vel: 0.3
  max_vel_theta: 1.0
  max_vel_trans: 0.55
  max_vel_x: 0.3
  max_vel_y: 0.3
  min_rot_vel: 0.1
  min_trans_vel: 0.1
  min_vel_theta: 0.4
  min_vel_trans: 0.1
  min_vel_x: 0.0
  min_vel_y: -0.3
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 0.6
  prune_plan: false
  restore_defaults: false
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.7
  stop_time_buffer: 0.2
  theta_stopped_vel: 0.1
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 12
  vx_samples: 6
  vy_samples: 6
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  
